### ISSUE TITLE
刷题失败

### ISSUE THREAD

**Issue by M1saka10010** [Mufanc/iSmartAuto2#6]
C:\Users\sunny\Desktop\iSmartAuto2-master>py main.py -vv flash -i 57829#48212a3d76bc4d038453be0342d401a1
2021-10-31 11:05:35.775 | INFO     | automaton.devtools:_verify:25 - 正在校验账号...
2021-10-31 11:05:35.787 | INFO     | automaton.devtools:wait_for_page:49 - 等待可用页面...
2021-10-31 11:05:35.981 | INFO     | automaton.devtools:_verify:43 - 校验通过！
2021-10-31 11:05:35.992 | INFO     | automaton.devtools:wait_for_page:49 - 等待可用页面...
2021-10-31 11:05:36.001 | INFO     | automaton.spider.spider:login:33 - 正在获取验证码...
2021-10-31 11:05:36.167 | INFO     | automaton.spider.captcha.captcha:recognize:35 - 识别结果：7421
2021-10-31 11:05:36.262 | DEBUG    | automaton.spider.spider:login:50 - {'code': -26, 'msg': '生成Tgt成功'}
2021-10-31 11:05:36.263 | INFO     | automaton.spider.spider:user_info:141 - 正在获取用户信息...
2021-10-31 11:05:36.854 | INFO     | automaton.spider.spider:book_info:147 - 正在获取书籍信息...
2021-10-31 11:05:36.949 | DEBUG    | automaton.spider.spider:book_info:154 - Ticket: ST-21879084-BDLa3i5OWdTZlp0cwm7I-cas01.example.org
Traceback (most recent call last):
  File "C:\Users\sunny\Desktop\iSmartAuto2-master\main.py", line 44, in <module>
    loop.run_until_complete(main())
  File "C:\Users\sunny\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\sunny\Desktop\iSmartAuto2-master\main.py", line 35, in main
    await utils.flash_by_id(args.id)
  File "C:\Users\sunny\Desktop\iSmartAuto2-master\automaton\utils.py", line 97, in flash_by_id
    await _flash(*identity.split('#'), spider)
  File "C:\Users\sunny\Desktop\iSmartAuto2-master\automaton\utils.py", line 90, in _flash
    book_type = (await spider.book_info(book_id))['bookType']
  File "C:\Users\sunny\Desktop\iSmartAuto2-master\automaton\spider\spider.py", line 171, in book_info
    return book_info['data']
KeyError: 'data'

**Comment by Mufanc** [comment]
clone 一下最新的代码，然后查看详细日志

**Comment by Mufanc** [comment]
教材是视听说吗？我只有视听说的课程，抓的也都是视听说的 API，不同课程的 bookType （也就是在 spider.py 170 行提交的参数）可能不同

**Comment by M1saka10010** [comment]
教材全名 大学体验英语视听说1

**Comment by Mufanc** [comment]
看来教材不一样（也许 bookType 不同罢）抓一下包然后改成你的大概就没问题了（？）

**Comment by hydrogen363** [comment]
抓包显示 大学体验英语视听说1 的bookid=1，改spider.py后父节点错误
`bookId=48212a3d76bc4d038453be0342d401a1&bookType=1&courseId=57829`

**Comment by hydrogen363** [comment]
你的邮件我收到了。I have received your email.
